language: node_js
node_js:
  - "6"

# stages:
#   - name: prod 
#     if: branch = master
#   - name: stage
#     if: branch != master

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: prod 
      script:
        - npm install -g serverless
        - sls deploy -s prod
      if: branch = master AND type != pull_request

    - stage: feature
      script:
        - npm install -g serverless
        - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
        - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH" 
        # - sls deploy -s ${BRANCH}
    # - stage: stage
    #   script:
    #     - npm install -g serverless
    #     - sls deploy -s stage
    #   if: type = pull_request

    # - stage: dev
    #   script:
    #     - npm install -g serverless
    #     - sls deploy -s dev
    #   if: branch != master AND type != pull_request

# script:
#   - npm install -g serverless
#   - sls deploy -s prod