language: node_js
node_js:
  - "6"

env:
  global:
    BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

service: mongodb

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: prod 
      script:
        - npm install -g serverless
        - yarn test
        - sls deploy -s prod
      if: branch = master AND type != pull_request

    # - stage: stage
    #   script:
    #     - npm install -g serverless
    #     - sls deploy -s stage
    #   if: type = pull_request

    - stage: dev
      before_script:
        - mongo adio-groups-test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
      script:
        # - sleep 15
        - yarn test
        - npm install -g serverless
        - sls deploy -s dev
      if: branch != master AND type != pull_request