language: node_js
node_js:
  - "6"

install:
  - npm install -g serverless

jobs:
  include:
    - stage: deploy to prod
      script: sls deploy -s prod
      if: branch = master

    - stage: deploy to stage
      script: sls deploy -s stage
      if: branch != master

# script:
#   - npm install -g serverless
#   - sls deploy -s prod